table Vendas
	lineageTag: b0efb266-f5d4-4e3e-b8f2-b7052e7796a1

	measure Test = SumTwoNumbers( SUM( Vendas[QtdItens] ), SUM( Vendas[ValorTotal] ) )
		formatString: \$#,0.###############;(\$#,0.###############);\$#,0.###############
		lineageTag: 8c3a1c0d-a5d2-43cf-9a2a-98fa70e67f9b

		annotation PBI_FormatHint = {"currencyCulture":"en-US"}

	column DataEmissao
		dataType: dateTime
		formatString: Long Date
		lineageTag: d05c965c-09e2-4659-a535-1d062c70f6fe
		summarizeBy: none
		sourceColumn: DataEmissao

		variation Variation
			isDefault
			relationship: 77a7026c-f04a-4700-b0fc-60c43b365da0
			defaultHierarchy: LocalDateTable_beafb70a-400a-4e0e-8ca8-f080575de602.'Date Hierarchy'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column NFe
		dataType: string
		lineageTag: bcc11b03-c6c4-4921-b14a-983619ffc877
		summarizeBy: none
		sourceColumn: NFe

		annotation SummarizationSetBy = Automatic

	column cdProduto
		dataType: int64
		formatString: 0
		lineageTag: ae60dd5e-0d5a-4367-88a6-0774db77999f
		summarizeBy: sum
		sourceColumn: cdProduto

		annotation SummarizationSetBy = Automatic

	column Produto
		dataType: string
		lineageTag: f55787c6-8913-47de-9b27-5ab19e78202b
		summarizeBy: none
		sourceColumn: Produto

		annotation SummarizationSetBy = Automatic

	column 'Grupo Produto'
		dataType: string
		lineageTag: 7fc64485-d3d8-4ec6-b2e0-4e852d7d64dc
		summarizeBy: none
		sourceColumn: Grupo Produto

		annotation SummarizationSetBy = Automatic

	column 'Linha Produto'
		dataType: string
		lineageTag: 5a922b04-c37a-4a5f-910d-477cd41f6498
		summarizeBy: none
		sourceColumn: Linha Produto

		annotation SummarizationSetBy = Automatic

	column cdVendedor
		dataType: int64
		formatString: 0
		lineageTag: a5cc8280-ac05-4b22-923c-57c6a8b91b4b
		summarizeBy: sum
		sourceColumn: cdVendedor

		annotation SummarizationSetBy = Automatic

	column Vendedor
		dataType: string
		lineageTag: 4c40c745-c40d-4307-ada9-5c941ba4c04d
		summarizeBy: none
		sourceColumn: Vendedor

		annotation SummarizationSetBy = Automatic

	column Supervisor
		dataType: string
		lineageTag: 24dd0981-7c62-42e8-b5aa-80126cf4eaa1
		summarizeBy: none
		sourceColumn: Supervisor

		annotation SummarizationSetBy = Automatic

	column Gerente
		dataType: string
		lineageTag: 6b61d8b5-c494-4e70-8986-476e4d7da2a8
		summarizeBy: none
		sourceColumn: Gerente

		annotation SummarizationSetBy = Automatic

	column 'Equipe Vendas'
		dataType: string
		lineageTag: 581a91ac-8fc5-4357-bda7-90d79bfbdd7f
		summarizeBy: none
		sourceColumn: Equipe Vendas

		annotation SummarizationSetBy = Automatic

	column QtdItens
		dataType: int64
		formatString: 0
		lineageTag: b2f1e5fa-968a-4e7a-a3c3-0b34190fecf8
		summarizeBy: sum
		sourceColumn: QtdItens

		annotation SummarizationSetBy = Automatic

	column ValorUnitario
		dataType: double
		lineageTag: 8671711b-ab17-4b8e-8495-cd15b4bb84d9
		summarizeBy: sum
		sourceColumn: ValorUnitario

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column ValorTotal
		dataType: decimal
		lineageTag: 33fce849-f8bd-491f-81e7-ee0c4d46fcf8
		summarizeBy: sum
		sourceColumn: ValorTotal

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	partition Vendas = m
		mode: import
		source =
				let
				    Source = Excel.Workbook(File.Contents("C:\Users\Pedro_Carvalho1\OneDrive - EPAM\Documents\Projects\Power BI\Leo Karpa Xperiun\Power Query Essencial\02. Power Query Essencial\BaseDados\Vendas.xlsx"), null, true),
				    Planilha1_Sheet = Source{[Item="Planilha1",Kind="Sheet"]}[Data],
				    #"Promoted Headers" = Table.PromoteHeaders(Planilha1_Sheet, [PromoteAllScalars=true]),
				    #"Changed Type" = Table.TransformColumnTypes(#"Promoted Headers",{{"DataEmissao", type date}, {"NFe", type text}, {"cdProduto", Int64.Type}, {"Produto", type text}, {"Grupo Produto", type text}, {"Linha Produto", type text}, {"cdVendedor", Int64.Type}, {"Vendedor", type text}, {"Supervisor", type text}, {"Gerente", type text}, {"Equipe Vendas", type text}, {"QtdItens", Int64.Type}, {"ValorUnitario", type number}}),
				    #"Inserted Multiplication" = Table.AddColumn(#"Changed Type", "Multiplication", each [QtdItens] * [ValorUnitario], Currency.Type),
				    #"Renamed Columns" = Table.RenameColumns(#"Inserted Multiplication",{{"Multiplication", "ValorTotal"}})
				in
				    #"Renamed Columns"

	annotation PBI_NavigationStepName = Navigation

	annotation PBI_ResultType = Table

